version: '3'
services:
  backend:
    build: ../app   
    hostname: server1
    env_file:
      - ../app/.env
    # environment:
    #   - PORT=5050 
    deploy:
     replicas: 3
     restart_policy:
       max_attempts: 3
       condition: on-failure       
     update_config:
       parallelism: 3
       delay: 10s
    networks:
      - loadbalancing
      


  nginx:
    build: ../nginx
    ports:
      - "4000:80"
    networks:
      - loadbalancing
    depends_on:
      - backend

networks:
  loadbalancing:
